### ISSUE TITLE
CronJobs throws Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by dennismetz** [BrainAppeal/campus_events_connector#2]
Everytime we run the cronjob to import the updated news it throws the warnings (or error in dev-context):

PHP Warning
Core: Error handler (BE): PHP Warning: Invalid argument supplied for foreach() in /path_to_prject/typo3conf/ext/campus_events_connector/Classes/Importer/ObjectGenerator/ImportObjectGenerator.php line 90

TYPO3 v9.5.22-9.5.24
PHP 7.2.5
CronJob every Minute
campus_events_connector 1.0.6 to 1.0.8

Additional:
campus_events_convert2news 1.0.4 to 1.0.5

**Comment by brain-appeal** [comment]
Thank you for your Feedback. We will have a look at this.

**Comment by brain-appeal** [comment]
Release 1.0.9 (cf2753e9c7b1bad294d0a04d6e18f35979cff48a) is now available and contains fixes for this problem.
