### ISSUE TITLE
Duplicate Events listed in Frontend

### ISSUE THREAD

**Issue by dennismetz** [BrainAppeal/campus_events_connector#3]
campus_events_connector 1.0.9
campus_events_frontend 1.0.3

The events are displayed twice in the frontend

Events->List
Events from the future

**Comment by brain-appeal** [comment]
Could you please give a little more information. 

* Is the data imported multiple times? So the data records in list view are duplicated or is it a view problem?
* Did you try to delete all imported items in list view and rerun the import and clear caches? Does this already solve the problem?

**Comment by dennismetz** [comment]
Hi, 
looks like the Events where imported twice while updating from 1.0.6 to 1.0.9.
We deleted all Events from the Backend and started the CronJob again, importing all Events and now it´s working fine.
