### ISSUE TITLE
News 11.x compatibility

### ISSUE THREAD

**Issue by dennismetz** [BrainAppeal/campus_events_connector#7]
Hi,
what about the News 11.x compatibility? Is it in planning?

Would be important for us for the following extensions:
campus_events_connector
campus_events_convert2news
campus_events_frontend

Greetings Dennis

**Comment by bahammes** [comment]
Hello,

we have released campus_events_convert2news v3.0.3
This version is compatible to news >= 11.0.0
https://github.com/BrainAppeal/campus_events_convert2news
